KDT-NES/NES

- config/urls.py
- templates/base.html
config 폴더의 urls에서 사용하지 않는 url 2개 주석처리
templates 의 base.html 에서 Naver => Never 로 변경
Close #9
> docs: url,templates 이름 수정

- articles/templates/articles/main.html
- config/settings.py
- static/css/main.css
- templates/base.html
> feat/static 추가

- orders/admin.py
- orders/apps.py
- orders/models.py
- orders/tests.py
- orders/views.py
> feat: Add orders

- main/admin.py
- main/apps.py
- main/models.py
- main/tests.py
- main/urls.py
- main/views.py
> feat: 개발용 페이지 추가

- main/templates/main/main.html
- main/urls.py
- main/views.py
인포 페이지로 가는 링크 삭제하고 자잘한 부분 수정
Close #51
> fix: 개발용 메인 페이지 오작동 수정

- accounts/views.py
- config/urls.py
- questions/models.py
- questions/templates/questions/create.html
- questions/templates/questions/index.html
- questions/urls.py
- questions/views.py
> feat: Q&A 페이지 생성 #62

- accounts/templates/accounts/index.html
- accounts/templates/accounts/login.html
- accounts/views.py
login 가능하게 값들 넘겨주는 부분 수정함.
url 들도 login 으로 넘어가게 설정함
Close #63
> feat: login 설정, url 수정

- notes/templates/notes/index.html
- notes/views.py
> feat: notes 페이지에 페이지네이션 추가 #74

- static/style/base2.css
- templates/base2.html
> feat: base2 화면 구현 #72

- accounts/templates/accounts/signup.html
- templates/base.html
- 모달이 오작동하는 현상을 수정하였습니다.
- 앞으로 모달 작성법 :
- 1. 대상 모달에 아래와 같이 id 를 준다.
- 숫자는 0 부터 시작
- id = "modal{숫자}" ex) "modal0"
- 2. 모달 버튼에 아래와 같이 id 를 준다.
- id = "modal-btn{숫자}" ex) "modal-btn0"
- 3. 모달 버튼의 data-bs-target 에 아래와 같이 모달 아이디를 준다.
- "#modal{숫자}" ex) "#modal0" Close #69
> fix: simplebar <-> modal 호환

- articles/templates/articles/loading.html
- static/script/loading.js
- static/style/loading.css
- templates/start.html
- loading page 구현
- start 페이지 수정 (깜박깜박 커서 추가)
close #71
> feat: loading page 구현 & start page 수정

- accounts/templates/accounts/profile.html
profile에서 각 요소들에 링크 설정 및 조건문 추가
> feat: profile에서 링크 설정 및 조건문 추가 #88

- accounts/views.py
> feat: 카카오 로그인 로직 재설정 #94

- static/style/post.css
> post.css 커밋

- static/style/profile.css
프로필 페이지 확대되거나 화면 크기에 따른 글자 크기 조절
Close #102
> fix: 프로필 페이지 폰트 크기조정

- accounts/templates/accounts/profile.html
- static/style/profile.css
profile height에 따른 반응형도 추가 + 작가 인증 버튼 생성
> fix: profile 페이지 높이 수정

- articles/templates/articles/datail2.html
- static/script/articles_detail.js
- static/style/articles_detail.css
- 초기 화면
- 사진 클릭 후 (댓글 있을 때 스크롤)
close #96
> feat: 디테일 화면 구현 #96

- static/style/articles_detail.css
> feat: 디테일 페이지 미디어쿼리 화면 구현 #108

- questions/templates/questions/index.html
- static/style/questions.css
너비에 따른 Q&A 페이지 디자인 구현
Close #106
> feat:question 페이지 모습 구현

- articles/templates/articles/index.html
- static/style/articles_index.css
> feat: index 이미지 수정 및 소개 박스 위치 이동

- static/style/ticket.css
- templates/ticket.html
> feat: 티켓 화면 구현 #117

- articles/templates/articles/main.html
- articles/views.py
> fix: articles 메인 typeerror 수정

- accounts/templates/accounts/profile.html
- accounts/templates/accounts/signup.html
- accounts/views.py
- notes/templates/notes/index.html
- notes/views.py
- templates/base.html
> feat: 편지 삭제 비동기 구현 #122

- notes/templates/notes/index.html
- notes/templates/notes/send.html
> feat: 편지함 로직 재설정 #123

- static/script/ticket_machine.js
- static/style/ticket_machine.css
- templates/ticket_machine.html
> feat: 티켓 머신 구현 #130

- orders/templates/orders/mycart.html
- orders/templates/orders/payment.html
- orders/urls.py
- orders/views.py
- 장바구니 삭제 기능 미완성
- 사용자 정보 폼 받아오기 미완성
close #136
> fix: 결제 사용자 정보 폼 수정 미완성 #136

- orders/templates/orders/mycart.html
- orders/urls.py
- orders/views.py
> feat: 장바구니 삭제 비동기 구현 미완성 #143

- articles/templates/articles/search.html
- static/style/main.css
1. search menu 버튼 스타일 수정
2. search 페이지네이션 스타일 수정
> fix: search menu 수정 #151

- articles/templates/articles/detail.html
- articles/views.py
article detail 페이지 좋아요 비동기 처리 구현
close #153
> feat: article detail 페이지 좋아요 비동기 #153

- articles/templates/articles/main.html
articles/main에서 각 카테고리 별 부가설명 추가
> feat: articles/main 카테고리 설명 추가

- accounts/forms.py
- accounts/templates/accounts/profile.html
- accounts/templates/accounts/signup.html
- accounts/views.py
> feat: 프로필 작가 인증시 작품등록, 인증마크 비동기 구현 #162

- static/style/login.css
> fix: login 폼 반응형 수정

- questions/admin.py
> feat: 슈퍼유저 생성 #171

- static/style/login.css
> fix: login respone 수정

- static/style/signup.css
> fix: singup 페이지 반응형조정

- articles/templates/articles/detail.html
- articles/views.py
로그인 한 사람만 댓글 수정삭제 하게 바꾸고 작품 삭제도 동일인물인 경우에만 삭제되도록 바꿈 Close #188
> feat: 댓글쓰기 로그인 관련

- orders/templates/orders/payment.html
띄어져있는 경우 작동을 안하기때문에 주석 추가하고 고침
Close #205
> fix: payment.html 20번째 줄 주석추가

- articles/templates/articles/create.html
- articles/templates/articles/update.html
- static/style/upload.css
> fix: 작품등록 수정페이지 반응형 수정

- notes/templates/notes/index.html
- notes/templates/notes/send.html
> feat: notes쪽 accounts 네이밍변경 #211

- articles/templates/articles/detail.html
articles/detail 작가만 작품 수정 및 삭제
> feat: articles/detail 작가만 작품 수정 및 삭제

- articles/forms.py
- articles/models.py
- orders/templates/orders/offer.html
- orders/urls.py
- orders/views.py
> feat: offer 모델 추가 #216

- accounts/templates/accounts/login.html
- accounts/templates/accounts/recently.html
- accounts/urls.py
- accounts/views.py
- articles/templates/articles/main.html
- articles/views.py
- orders/templates/orders/mycart.html
- static/style/recently.css
- templates/base.html
1. 최근 본 작품목록 페이지를 만들엇음
2. sweetalert 적용했음 Close #231
> feat: 최근 본 작품목록 + sweetalert

- articles/templates/articles/detail.html
- articles/templates/articles/main.html
- orders/templates/orders/offer.html
- static/style/offer.css
- orders/offer nav바 추가
- articles/detail nav바 url 추가
- orders/offer 글자크기 수정
> fix: orders/offer nav바 추가

- articles/templates/articles/detail.html
- articles/templates/articles/index.html
- articles/templates/articles/main.html
- articles/views.py
- orders/templates/orders/info.html
- orders/templates/orders/mycart.html
navbar가 존재하는 페이지에 해당 페이지들 연결
orders/payment, complete 연결 X (작업중)
> fix: 전체 페이지 navbar 링크 연결

- orders/templates/orders/complete.html
- orders/templates/orders/info.html
- orders/templates/orders/mycart.html
- orders/templates/orders/offer.html
- orders/templates/orders/payment.html
- questions/templates/questions/index.html
- static/style/myquestion.css
- static/style/questions.css
> feat: QnA 질문 입력 및 파란색 배경 제거

- notes/templates/notes/send.html
> feat: notes/send css 수정 #246

- accounts/templates/accounts/profile.html
- static/style/profile.css
> feat: accounts페이지 판매완료 soldout표시 및 하트추가 #248

- articles/templates/articles/index.html
- static/style/articles_index.css
좌우 스크롤구현했고 스크롤에 따른 배경색 변화 줬습니다.
> feat: 좌우 스크롤 및 스크롤에따른 색변화

- orders/templates/orders/complete.html
- static/style/complete.css
- orders/complete 2개 이상 구매 시 구매완료된 작품 출력 for문 수정
- orders/complete CSS margin 수정
> fix: orders/complete for문 수정

- orders/templates/orders/complete.html
- orders/complete 작가 프로필 출력되도록 수정
- orders/complete navbar 수정
> fix: orders/complete 작가 프로필 수정

- accounts/templates/accounts/profile.html
- static/style/profile.css
- 구매목록 아이콘 제거
- 톱니바퀴 크기 수정 (svg태그로 교체)
- 네브바 추가
- 저장된 작품 카드의 하트 크기 조금 확대
> fix: profile CSS 수정

- articles/templates/articles/main.html
- articles/templates/articles/search.html
- static/script/ticket_machine.js
- static/style/main.css
searh 페이지네이션 "<"삭제된거 복구, button border 수정함
> fix: search button border 수정

- orders/templates/orders/mycart.html
- orders/templates/orders/offer.html
> fix: orders/offer, orders/mycart 알림창 문구 수정

- static/style/signup.css
> fix: 회원가입 로고 크기 수정

- articles/templates/articles/create.html
- articles/templates/articles/update.html
- static/style/upload.css
> fix: 제작년도 숫자로 제한둠

- notes/templates/notes/index.html
- static/style/post.css
> fix: 쪽지함 반응형 수정 #282

- static/style/profile_update.css
- static/style/signup.css
> fix: 로그인, 작품 등록 스타일 수정 #288

- articles/templates/articles/main.html
> fix: articles/main 전체작품 페이지네이션 제거

- accounts/templates/accounts/login.html
> feat: 아이디/비밀번호 찾기 알림창

- articles/templates/articles/index.html
- articles/templates/articles/main.html
- articles/views.py
> fix: articles 카테고리 조소 수정

- orders/templates/orders/offer.html
> fix: articles/search 페이지네이션 수정

- orders/templates/orders/offer.html
> fix: oders/offer 수락버튼 수정

- orders/templates/orders/offer.html
- static/style/offer.css
> fix: orders/offer 수락버튼 수정

- accounts/templates/accounts/profile.html
- articles/templates/articles/about.html
- articles/templates/articles/create.html
- articles/templates/articles/detail.html
- articles/templates/articles/index.html
- articles/templates/articles/main.html
- articles/templates/articles/search.html
- orders/templates/orders/complete.html
- orders/templates/orders/info.html
- orders/templates/orders/offer.html
- orders/templates/orders/payment.html
- static/style/payment.css
payment 뒤로가기 버튼, 장바구니 네브바 추가 반응형 조정
> fix: payment 뒤로가기 버튼, 장바구니 네브바 추가

- articles/templates/articles/detail.html
> 장바구니 detail 페이지 수정
